# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui',
# licensing of 'dialog.ui' applies.
#
# Created: Wed Jan 22 18:23:27 2020
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1390, 820)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(570, 10, 811, 801))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.preview_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.preview_layout.setSpacing(10)
        self.preview_layout.setContentsMargins(10, 10, 10, 10)
        self.preview_layout.setObjectName("preview_layout")
        self.pre_mask = QtWidgets.QWidget(self.gridLayoutWidget)
        self.pre_mask.setAutoFillBackground(False)
        self.pre_mask.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pre_mask.setObjectName("pre_mask")
        self.pre_mask_label = QtWidgets.QLabel(self.pre_mask)
        self.pre_mask_label.setGeometry(QtCore.QRect(9, 9, 65, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pre_mask_label.setFont(font)
        self.pre_mask_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_mask_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.pre_mask_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pre_mask_label.setObjectName("pre_mask_label")
        self.preview_layout.addWidget(self.pre_mask, 1, 0, 1, 1)
        self.generated = QtWidgets.QWidget(self.gridLayoutWidget)
        self.generated.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.generated.setObjectName("generated")
        self.generated_label = QtWidgets.QLabel(self.generated)
        self.generated_label.setGeometry(QtCore.QRect(9, 9, 72, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.generated_label.setFont(font)
        self.generated_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.generated_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.generated_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.generated_label.setObjectName("generated_label")
        self.preview_layout.addWidget(self.generated, 0, 1, 1, 1)
        self.post_mask = QtWidgets.QWidget(self.gridLayoutWidget)
        self.post_mask.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.post_mask.setObjectName("post_mask")
        self.post_mask_label = QtWidgets.QLabel(self.post_mask)
        self.post_mask_label.setGeometry(QtCore.QRect(9, 9, 72, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.post_mask_label.setFont(font)
        self.post_mask_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.post_mask_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.post_mask_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.post_mask_label.setObjectName("post_mask_label")
        self.preview_layout.addWidget(self.post_mask, 1, 1, 1, 1)
        self.ideal = GraphicsView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ideal.sizePolicy().hasHeightForWidth())
        self.ideal.setSizePolicy(sizePolicy)
        self.ideal.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ideal.setObjectName("ideal")
        self.ideal_label = QtWidgets.QLabel(self.ideal)
        self.ideal_label.setGeometry(QtCore.QRect(9, 9, 40, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.ideal_label.setFont(font)
        self.ideal_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ideal_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.ideal_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ideal_label.setObjectName("ideal_label")
        self.preview_layout.addWidget(self.ideal, 0, 0, 1, 1)
        self.slm_parameters = QtWidgets.QGroupBox(Dialog)
        self.slm_parameters.setGeometry(QtCore.QRect(20, 20, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slm_parameters.setFont(font)
        self.slm_parameters.setObjectName("slm_parameters")
        self.screen_size_label = QtWidgets.QLabel(self.slm_parameters)
        self.screen_size_label.setGeometry(QtCore.QRect(50, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.screen_size_label.setFont(font)
        self.screen_size_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.screen_size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.screen_size_label.setObjectName("screen_size_label")
        self.pixel_size_label = QtWidgets.QLabel(self.slm_parameters)
        self.pixel_size_label.setGeometry(QtCore.QRect(30, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_size_label.setFont(font)
        self.pixel_size_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pixel_size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixel_size_label.setObjectName("pixel_size_label")
        self.pixel_size_spinbox = QtWidgets.QDoubleSpinBox(self.slm_parameters)
        self.pixel_size_spinbox.setGeometry(QtCore.QRect(150, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_size_spinbox.setFont(font)
        self.pixel_size_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.pixel_size_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.pixel_size_spinbox.setDecimals(1)
        self.pixel_size_spinbox.setMinimum(1.0)
        self.pixel_size_spinbox.setMaximum(100.0)
        self.pixel_size_spinbox.setSingleStep(0.1)
        self.pixel_size_spinbox.setProperty("value", 8.2)
        self.pixel_size_spinbox.setObjectName("pixel_size_spinbox")
        self.focal_length_label = QtWidgets.QLabel(self.slm_parameters)
        self.focal_length_label.setGeometry(QtCore.QRect(20, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focal_length_label.setFont(font)
        self.focal_length_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.focal_length_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focal_length_label.setObjectName("focal_length_label")
        self.focal_length_spinbox = QtWidgets.QSpinBox(self.slm_parameters)
        self.focal_length_spinbox.setGeometry(QtCore.QRect(150, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focal_length_spinbox.setFont(font)
        self.focal_length_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.focal_length_spinbox.setMaximum(1000)
        self.focal_length_spinbox.setProperty("value", 500)
        self.focal_length_spinbox.setObjectName("focal_length_spinbox")
        self.screensize_combobox = QtWidgets.QComboBox(self.slm_parameters)
        self.screensize_combobox.setGeometry(QtCore.QRect(150, 30, 81, 22))
        self.screensize_combobox.setObjectName("screensize_combobox")
        self.objective_parameters = QtWidgets.QGroupBox(Dialog)
        self.objective_parameters.setGeometry(QtCore.QRect(20, 340, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.objective_parameters.setFont(font)
        self.objective_parameters.setObjectName("objective_parameters")
        self.objective_magnification_label = QtWidgets.QLabel(self.objective_parameters)
        self.objective_magnification_label.setGeometry(QtCore.QRect(50, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.objective_magnification_label.setFont(font)
        self.objective_magnification_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.objective_magnification_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.objective_magnification_label.setObjectName("objective_magnification_label")
        self.objective_magnification_spinbox = QtWidgets.QSpinBox(self.objective_parameters)
        self.objective_magnification_spinbox.setGeometry(QtCore.QRect(150, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.objective_magnification_spinbox.setFont(font)
        self.objective_magnification_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.objective_magnification_spinbox.setMaximum(100)
        self.objective_magnification_spinbox.setProperty("value", 10)
        self.objective_magnification_spinbox.setObjectName("objective_magnification_spinbox")
        self.objective_na_label = QtWidgets.QLabel(self.objective_parameters)
        self.objective_na_label.setGeometry(QtCore.QRect(30, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.objective_na_label.setFont(font)
        self.objective_na_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.objective_na_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.objective_na_label.setObjectName("objective_na_label")
        self.objective_na_spinbox = QtWidgets.QDoubleSpinBox(self.objective_parameters)
        self.objective_na_spinbox.setGeometry(QtCore.QRect(150, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.objective_na_spinbox.setFont(font)
        self.objective_na_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.objective_na_spinbox.setMaximum(2.0)
        self.objective_na_spinbox.setSingleStep(0.01)
        self.objective_na_spinbox.setProperty("value", 0.25)
        self.objective_na_spinbox.setObjectName("objective_na_spinbox")
        self.tube_lens_spinbox = QtWidgets.QSpinBox(self.objective_parameters)
        self.tube_lens_spinbox.setGeometry(QtCore.QRect(150, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tube_lens_spinbox.setFont(font)
        self.tube_lens_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.tube_lens_spinbox.setMaximum(1000)
        self.tube_lens_spinbox.setSingleStep(1)
        self.tube_lens_spinbox.setProperty("value", 200)
        self.tube_lens_spinbox.setObjectName("tube_lens_spinbox")
        self.tube_lens_label = QtWidgets.QLabel(self.objective_parameters)
        self.tube_lens_label.setGeometry(QtCore.QRect(30, 90, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tube_lens_label.setFont(font)
        self.tube_lens_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tube_lens_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tube_lens_label.setObjectName("tube_lens_label")
        self.mask_parameters = QtWidgets.QGroupBox(Dialog)
        self.mask_parameters.setGeometry(QtCore.QRect(20, 170, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_parameters.setFont(font)
        self.mask_parameters.setObjectName("mask_parameters")
        self.mask_od_label = QtWidgets.QLabel(self.mask_parameters)
        self.mask_od_label.setGeometry(QtCore.QRect(10, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_od_label.setFont(font)
        self.mask_od_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mask_od_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_od_label.setObjectName("mask_od_label")
        self.mask_od_spinbox = QtWidgets.QDoubleSpinBox(self.mask_parameters)
        self.mask_od_spinbox.setGeometry(QtCore.QRect(90, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_od_spinbox.setFont(font)
        self.mask_od_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_od_spinbox.setDecimals(3)
        self.mask_od_spinbox.setMaximum(5.0)
        self.mask_od_spinbox.setSingleStep(0.001)
        self.mask_od_spinbox.setProperty("value", 3.824)
        self.mask_od_spinbox.setObjectName("mask_od_spinbox")
        self.mask_id_label = QtWidgets.QLabel(self.mask_parameters)
        self.mask_id_label.setGeometry(QtCore.QRect(10, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_id_label.setFont(font)
        self.mask_id_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mask_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mask_id_label.setObjectName("mask_id_label")
        self.mask_id_spinbox = QtWidgets.QDoubleSpinBox(self.mask_parameters)
        self.mask_id_spinbox.setGeometry(QtCore.QRect(90, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_id_spinbox.setFont(font)
        self.mask_id_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_id_spinbox.setDecimals(3)
        self.mask_id_spinbox.setMaximum(5.0)
        self.mask_id_spinbox.setSingleStep(0.001)
        self.mask_id_spinbox.setProperty("value", 2.689)
        self.mask_id_spinbox.setObjectName("mask_id_spinbox")
        self.mask_od_na = QtWidgets.QLabel(self.mask_parameters)
        self.mask_od_na.setGeometry(QtCore.QRect(180, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_od_na.setFont(font)
        self.mask_od_na.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mask_od_na.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_od_na.setObjectName("mask_od_na")
        self.mask_id_na = QtWidgets.QLabel(self.mask_parameters)
        self.mask_id_na.setGeometry(QtCore.QRect(180, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mask_id_na.setFont(font)
        self.mask_id_na.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mask_id_na.setAlignment(QtCore.Qt.AlignCenter)
        self.mask_id_na.setObjectName("mask_id_na")
        self.from_mask_file = QtWidgets.QPushButton(self.mask_parameters)
        self.from_mask_file.setEnabled(False)
        self.from_mask_file.setGeometry(QtCore.QRect(110, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.from_mask_file.setFont(font)
        self.from_mask_file.setObjectName("from_mask_file")
        self.system_parameters = QtWidgets.QGroupBox(Dialog)
        self.system_parameters.setGeometry(QtCore.QRect(20, 490, 251, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.system_parameters.setFont(font)
        self.system_parameters.setObjectName("system_parameters")
        self.wavelength_label = QtWidgets.QLabel(self.system_parameters)
        self.wavelength_label.setGeometry(QtCore.QRect(20, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wavelength_label.setFont(font)
        self.wavelength_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wavelength_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wavelength_label.setObjectName("wavelength_label")
        self.wavelength_spinbox = QtWidgets.QSpinBox(self.system_parameters)
        self.wavelength_spinbox.setGeometry(QtCore.QRect(150, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wavelength_spinbox.setFont(font)
        self.wavelength_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.wavelength_spinbox.setMinimum(350)
        self.wavelength_spinbox.setMaximum(1500)
        self.wavelength_spinbox.setProperty("value", 488)
        self.wavelength_spinbox.setObjectName("wavelength_spinbox")
        self.system_magnification_label = QtWidgets.QLabel(self.system_parameters)
        self.system_magnification_label.setGeometry(QtCore.QRect(10, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.system_magnification_label.setFont(font)
        self.system_magnification_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.system_magnification_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.system_magnification_label.setObjectName("system_magnification_label")
        self.system_magnification_spinbox = QtWidgets.QDoubleSpinBox(self.system_parameters)
        self.system_magnification_spinbox.setGeometry(QtCore.QRect(150, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.system_magnification_spinbox.setFont(font)
        self.system_magnification_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.system_magnification_spinbox.setDecimals(1)
        self.system_magnification_spinbox.setMaximum(500.0)
        self.system_magnification_spinbox.setSingleStep(0.1)
        self.system_magnification_spinbox.setProperty("value", 60.0)
        self.system_magnification_spinbox.setObjectName("system_magnification_spinbox")
        self.line_2 = QtWidgets.QFrame(self.system_parameters)
        self.line_2.setGeometry(QtCore.QRect(20, 90, 211, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dither_steps_label = QtWidgets.QLabel(self.system_parameters)
        self.dither_steps_label.setGeometry(QtCore.QRect(10, 120, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dither_steps_label.setFont(font)
        self.dither_steps_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dither_steps_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dither_steps_label.setObjectName("dither_steps_label")
        self.dither_steps_spinbox = QtWidgets.QSpinBox(self.system_parameters)
        self.dither_steps_spinbox.setGeometry(QtCore.QRect(150, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dither_steps_spinbox.setFont(font)
        self.dither_steps_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.dither_steps_spinbox.setMinimum(1)
        self.dither_steps_spinbox.setMaximum(200)
        self.dither_steps_spinbox.setProperty("value", 1)
        self.dither_steps_spinbox.setObjectName("dither_steps_spinbox")
        self.dither_interval_label = QtWidgets.QLabel(self.system_parameters)
        self.dither_interval_label.setGeometry(QtCore.QRect(10, 150, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dither_interval_label.setFont(font)
        self.dither_interval_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dither_interval_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dither_interval_label.setObjectName("dither_interval_label")
        self.dither_interval_spinbox = QtWidgets.QDoubleSpinBox(self.system_parameters)
        self.dither_interval_spinbox.setEnabled(False)
        self.dither_interval_spinbox.setGeometry(QtCore.QRect(150, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dither_interval_spinbox.setFont(font)
        self.dither_interval_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.dither_interval_spinbox.setSingleStep(0.01)
        self.dither_interval_spinbox.setObjectName("dither_interval_spinbox")
        self.bessel_parameters = QtWidgets.QGroupBox(Dialog)
        self.bessel_parameters.setGeometry(QtCore.QRect(300, 20, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_parameters.setFont(font)
        self.bessel_parameters.setFlat(False)
        self.bessel_parameters.setCheckable(True)
        self.bessel_parameters.setChecked(True)
        self.bessel_parameters.setObjectName("bessel_parameters")
        self.bessel_od_label = QtWidgets.QLabel(self.bessel_parameters)
        self.bessel_od_label.setGeometry(QtCore.QRect(10, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_od_label.setFont(font)
        self.bessel_od_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bessel_od_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bessel_od_label.setObjectName("bessel_od_label")
        self.bessel_od_spinbox = QtWidgets.QDoubleSpinBox(self.bessel_parameters)
        self.bessel_od_spinbox.setEnabled(False)
        self.bessel_od_spinbox.setGeometry(QtCore.QRect(90, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_od_spinbox.setFont(font)
        self.bessel_od_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.bessel_od_spinbox.setDecimals(3)
        self.bessel_od_spinbox.setMaximum(10.0)
        self.bessel_od_spinbox.setSingleStep(0.001)
        self.bessel_od_spinbox.setProperty("value", 3.824)
        self.bessel_od_spinbox.setObjectName("bessel_od_spinbox")
        self.bessel_id_label = QtWidgets.QLabel(self.bessel_parameters)
        self.bessel_id_label.setGeometry(QtCore.QRect(10, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_id_label.setFont(font)
        self.bessel_id_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bessel_id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bessel_id_label.setObjectName("bessel_id_label")
        self.bessel_id_spinbox = QtWidgets.QDoubleSpinBox(self.bessel_parameters)
        self.bessel_id_spinbox.setEnabled(False)
        self.bessel_id_spinbox.setGeometry(QtCore.QRect(90, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_id_spinbox.setFont(font)
        self.bessel_id_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.bessel_id_spinbox.setDecimals(3)
        self.bessel_id_spinbox.setMaximum(10.0)
        self.bessel_id_spinbox.setSingleStep(0.001)
        self.bessel_id_spinbox.setProperty("value", 2.689)
        self.bessel_id_spinbox.setObjectName("bessel_id_spinbox")
        self.bessel_od_na = QtWidgets.QLabel(self.bessel_parameters)
        self.bessel_od_na.setGeometry(QtCore.QRect(180, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_od_na.setFont(font)
        self.bessel_od_na.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bessel_od_na.setAlignment(QtCore.Qt.AlignCenter)
        self.bessel_od_na.setObjectName("bessel_od_na")
        self.bessel_id_na = QtWidgets.QLabel(self.bessel_parameters)
        self.bessel_id_na.setGeometry(QtCore.QRect(180, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bessel_id_na.setFont(font)
        self.bessel_id_na.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bessel_id_na.setAlignment(QtCore.Qt.AlignCenter)
        self.bessel_id_na.setObjectName("bessel_id_na")
        self.same_as_mask = QtWidgets.QCheckBox(self.bessel_parameters)
        self.same_as_mask.setGeometry(QtCore.QRect(20, 100, 121, 21))
        self.same_as_mask.setChecked(True)
        self.same_as_mask.setObjectName("same_as_mask")
        self.linear_bessel_array_parameters = QtWidgets.QGroupBox(Dialog)
        self.linear_bessel_array_parameters.setGeometry(QtCore.QRect(300, 180, 251, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linear_bessel_array_parameters.setFont(font)
        self.linear_bessel_array_parameters.setFlat(False)
        self.linear_bessel_array_parameters.setCheckable(True)
        self.linear_bessel_array_parameters.setChecked(True)
        self.linear_bessel_array_parameters.setObjectName("linear_bessel_array_parameters")
        self.n_beams_label = QtWidgets.QLabel(self.linear_bessel_array_parameters)
        self.n_beams_label.setGeometry(QtCore.QRect(50, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_beams_label.setFont(font)
        self.n_beams_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n_beams_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_beams_label.setObjectName("n_beams_label")
        self.n_beams_spinbox = QtWidgets.QSpinBox(self.linear_bessel_array_parameters)
        self.n_beams_spinbox.setGeometry(QtCore.QRect(150, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_beams_spinbox.setFont(font)
        self.n_beams_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.n_beams_spinbox.setMinimum(1)
        self.n_beams_spinbox.setMaximum(100)
        self.n_beams_spinbox.setObjectName("n_beams_spinbox")
        self.spacing_label = QtWidgets.QLabel(self.linear_bessel_array_parameters)
        self.spacing_label.setGeometry(QtCore.QRect(30, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spacing_label.setFont(font)
        self.spacing_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spacing_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spacing_label.setObjectName("spacing_label")
        self.spacing_spinbox = QtWidgets.QDoubleSpinBox(self.linear_bessel_array_parameters)
        self.spacing_spinbox.setGeometry(QtCore.QRect(150, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spacing_spinbox.setFont(font)
        self.spacing_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.spacing_spinbox.setDecimals(3)
        self.spacing_spinbox.setMaximum(100.0)
        self.spacing_spinbox.setSingleStep(0.001)
        self.spacing_spinbox.setProperty("value", 1.0)
        self.spacing_spinbox.setObjectName("spacing_spinbox")
        self.auto_spacing = QtWidgets.QCheckBox(self.linear_bessel_array_parameters)
        self.auto_spacing.setGeometry(QtCore.QRect(20, 170, 201, 21))
        self.auto_spacing.setObjectName("auto_spacing")
        self.fill_screen_checkbox = QtWidgets.QCheckBox(self.linear_bessel_array_parameters)
        self.fill_screen_checkbox.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.fill_screen_checkbox.setObjectName("fill_screen_checkbox")
        self.line = QtWidgets.QFrame(self.linear_bessel_array_parameters)
        self.line.setGeometry(QtCore.QRect(20, 100, 211, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fill_screen_spinbox = QtWidgets.QSpinBox(self.linear_bessel_array_parameters)
        self.fill_screen_spinbox.setEnabled(False)
        self.fill_screen_spinbox.setGeometry(QtCore.QRect(150, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fill_screen_spinbox.setFont(font)
        self.fill_screen_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.fill_screen_spinbox.setMaximum(100)
        self.fill_screen_spinbox.setProperty("value", 50)
        self.fill_screen_spinbox.setObjectName("fill_screen_spinbox")
        self.binarize_parameters = QtWidgets.QGroupBox(Dialog)
        self.binarize_parameters.setGeometry(QtCore.QRect(20, 700, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.binarize_parameters.setFont(font)
        self.binarize_parameters.setCheckable(False)
        self.binarize_parameters.setChecked(False)
        self.binarize_parameters.setObjectName("binarize_parameters")
        self.cropping_factor_label = QtWidgets.QLabel(self.binarize_parameters)
        self.cropping_factor_label.setGeometry(QtCore.QRect(40, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cropping_factor_label.setFont(font)
        self.cropping_factor_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cropping_factor_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cropping_factor_label.setObjectName("cropping_factor_label")
        self.cropping_factor_spinbox = QtWidgets.QDoubleSpinBox(self.binarize_parameters)
        self.cropping_factor_spinbox.setGeometry(QtCore.QRect(150, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cropping_factor_spinbox.setFont(font)
        self.cropping_factor_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.cropping_factor_spinbox.setMaximum(1.0)
        self.cropping_factor_spinbox.setSingleStep(0.01)
        self.cropping_factor_spinbox.setProperty("value", 0.05)
        self.cropping_factor_spinbox.setObjectName("cropping_factor_spinbox")
        self.simple_threshold = QtWidgets.QCheckBox(self.binarize_parameters)
        self.simple_threshold.setGeometry(QtCore.QRect(20, 30, 141, 21))
        self.simple_threshold.setChecked(True)
        self.simple_threshold.setTristate(False)
        self.simple_threshold.setObjectName("simple_threshold")
        self.regenerate = QtWidgets.QPushButton(Dialog)
        self.regenerate.setGeometry(QtCore.QRect(420, 500, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.regenerate.setFont(font)
        self.regenerate.setObjectName("regenerate")
        self.tiling_parameters = QtWidgets.QGroupBox(Dialog)
        self.tiling_parameters.setGeometry(QtCore.QRect(300, 410, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tiling_parameters.setFont(font)
        self.tiling_parameters.setFlat(False)
        self.tiling_parameters.setCheckable(True)
        self.tiling_parameters.setChecked(False)
        self.tiling_parameters.setObjectName("tiling_parameters")
        self.wavelength_spinbox_2 = QtWidgets.QSpinBox(self.tiling_parameters)
        self.wavelength_spinbox_2.setGeometry(QtCore.QRect(150, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wavelength_spinbox_2.setFont(font)
        self.wavelength_spinbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.wavelength_spinbox_2.setMinimum(0)
        self.wavelength_spinbox_2.setMaximum(1500)
        self.wavelength_spinbox_2.setProperty("value", 0)
        self.wavelength_spinbox_2.setObjectName("wavelength_spinbox_2")
        self.wavelength_label_2 = QtWidgets.QLabel(self.tiling_parameters)
        self.wavelength_label_2.setGeometry(QtCore.QRect(20, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wavelength_label_2.setFont(font)
        self.wavelength_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wavelength_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wavelength_label_2.setObjectName("wavelength_label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.pre_mask_label.setText(QtWidgets.QApplication.translate("Dialog", " Pre-Mask", None, -1))
        self.generated_label.setText(QtWidgets.QApplication.translate("Dialog", " Generated", None, -1))
        self.post_mask_label.setText(QtWidgets.QApplication.translate("Dialog", " Post-Mask", None, -1))
        self.ideal_label.setText(QtWidgets.QApplication.translate("Dialog", " Ideal ", None, -1))
        self.slm_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " SLM ", None, -1))
        self.screen_size_label.setText(QtWidgets.QApplication.translate("Dialog", "Screen Size:", None, -1))
        self.pixel_size_label.setText(QtWidgets.QApplication.translate("Dialog", "Pixel Size (um):", None, -1))
        self.focal_length_label.setText(QtWidgets.QApplication.translate("Dialog", "Focal Length (mm):", None, -1))
        self.objective_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " Objective ", None, -1))
        self.objective_magnification_label.setText(QtWidgets.QApplication.translate("Dialog", "Magnification:", None, -1))
        self.objective_na_label.setText(QtWidgets.QApplication.translate("Dialog", "NA:", None, -1))
        self.tube_lens_label.setText(QtWidgets.QApplication.translate("Dialog", "Tube Lens (mm):", None, -1))
        self.mask_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " Mask ", None, -1))
        self.mask_od_label.setText(QtWidgets.QApplication.translate("Dialog", "OD (mm):", None, -1))
        self.mask_id_label.setText(QtWidgets.QApplication.translate("Dialog", "ID (mm):", None, -1))
        self.mask_od_na.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.mask_id_na.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.from_mask_file.setText(QtWidgets.QApplication.translate("Dialog", "From Mask File", None, -1))
        self.system_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " System ", None, -1))
        self.wavelength_label.setText(QtWidgets.QApplication.translate("Dialog", "Wavelength (nm):", None, -1))
        self.system_magnification_label.setText(QtWidgets.QApplication.translate("Dialog", "Overall Magnification:", None, -1))
        self.dither_steps_label.setText(QtWidgets.QApplication.translate("Dialog", "# Dither Steps:", None, -1))
        self.dither_interval_label.setText(QtWidgets.QApplication.translate("Dialog", "Interval (um):", None, -1))
        self.bessel_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " Bessel ", None, -1))
        self.bessel_od_label.setText(QtWidgets.QApplication.translate("Dialog", "OD (mm):", None, -1))
        self.bessel_id_label.setText(QtWidgets.QApplication.translate("Dialog", "ID (mm):", None, -1))
        self.bessel_od_na.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.bessel_id_na.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.same_as_mask.setText(QtWidgets.QApplication.translate("Dialog", "Same as mask", None, -1))
        self.linear_bessel_array_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " Linear Bessel Array ", None, -1))
        self.n_beams_label.setText(QtWidgets.QApplication.translate("Dialog", "# Beams:", None, -1))
        self.spacing_label.setText(QtWidgets.QApplication.translate("Dialog", "Spacing (um):", None, -1))
        self.auto_spacing.setText(QtWidgets.QApplication.translate("Dialog", "Determine spacing from NA", None, -1))
        self.fill_screen_checkbox.setText(QtWidgets.QApplication.translate("Dialog", "Fill screen (%):", None, -1))
        self.binarize_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " Binarize ", None, -1))
        self.cropping_factor_label.setText(QtWidgets.QApplication.translate("Dialog", "Cropping Factor:", None, -1))
        self.simple_threshold.setText(QtWidgets.QApplication.translate("Dialog", "Simple Threshold", None, -1))
        self.regenerate.setText(QtWidgets.QApplication.translate("Dialog", "Regenerate", None, -1))
        self.tiling_parameters.setTitle(QtWidgets.QApplication.translate("Dialog", " Tiling ", None, -1))
        self.wavelength_label_2.setText(QtWidgets.QApplication.translate("Dialog", "Focus (um):", None, -1))

from pyqtgraph import GraphicsView
