# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog.ui'
##
## Created by: Qt User Interface Compiler version 5.14.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

from pyqtgraph import GraphicsView

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1290, 730)
        self.gridLayoutWidget = QWidget(Dialog)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(570, 10, 711, 711))
        self.preview_layout = QGridLayout(self.gridLayoutWidget)
        self.preview_layout.setSpacing(10)
        self.preview_layout.setObjectName(u"preview_layout")
        self.preview_layout.setContentsMargins(10, 10, 10, 10)
        self.pre_mask = QWidget(self.gridLayoutWidget)
        self.pre_mask.setObjectName(u"pre_mask")
        self.pre_mask.setAutoFillBackground(False)
        self.pre_mask.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.pre_mask_label = QLabel(self.pre_mask)
        self.pre_mask_label.setObjectName(u"pre_mask_label")
        self.pre_mask_label.setGeometry(QRect(0, 0, 81, 21))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75);
        self.pre_mask_label.setFont(font)
        self.pre_mask_label.setLayoutDirection(Qt.LeftToRight)
        self.pre_mask_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pre_mask_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.preview_layout.addWidget(self.pre_mask, 1, 0, 1, 1)

        self.post_mask = QWidget(self.gridLayoutWidget)
        self.post_mask.setObjectName(u"post_mask")
        self.post_mask.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.post_mask_label = QLabel(self.post_mask)
        self.post_mask_label.setObjectName(u"post_mask_label")
        self.post_mask_label.setGeometry(QRect(0, 0, 81, 21))
        self.post_mask_label.setFont(font)
        self.post_mask_label.setLayoutDirection(Qt.LeftToRight)
        self.post_mask_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.post_mask_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.preview_layout.addWidget(self.post_mask, 1, 2, 1, 1)

        self.ideal = GraphicsView(self.gridLayoutWidget)
        self.ideal.setObjectName(u"ideal")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ideal.sizePolicy().hasHeightForWidth())
        self.ideal.setSizePolicy(sizePolicy)
        self.ideal.setAcceptDrops(False)
        self.ideal.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        
        self.preview_layout.addWidget(self.ideal, 0, 0, 1, 1)

        self.generated = QWidget(self.gridLayoutWidget)
        self.generated.setObjectName(u"generated")
        self.generated.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.generated_label = QLabel(self.generated)
        self.generated_label.setObjectName(u"generated_label")
        self.generated_label.setGeometry(QRect(0, 0, 81, 21))
        self.generated_label.setFont(font)
        self.generated_label.setLayoutDirection(Qt.LeftToRight)
        self.generated_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.generated_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.preview_layout.addWidget(self.generated, 0, 2, 1, 1)

        self.slm_parameters = QGroupBox(Dialog)
        self.slm_parameters.setObjectName(u"slm_parameters")
        self.slm_parameters.setGeometry(QRect(20, 20, 251, 131))
        font1 = QFont()
        font1.setPointSize(10)
        self.slm_parameters.setFont(font1)
        self.screen_size_label = QLabel(self.slm_parameters)
        self.screen_size_label.setObjectName(u"screen_size_label")
        self.screen_size_label.setGeometry(QRect(50, 30, 91, 21))
        self.screen_size_label.setFont(font1)
        self.screen_size_label.setLayoutDirection(Qt.LeftToRight)
        self.screen_size_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pixel_size_label = QLabel(self.slm_parameters)
        self.pixel_size_label.setObjectName(u"pixel_size_label")
        self.pixel_size_label.setGeometry(QRect(30, 60, 111, 21))
        self.pixel_size_label.setFont(font1)
        self.pixel_size_label.setLayoutDirection(Qt.LeftToRight)
        self.pixel_size_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pixel_size_spinbox = QDoubleSpinBox(self.slm_parameters)
        self.pixel_size_spinbox.setObjectName(u"pixel_size_spinbox")
        self.pixel_size_spinbox.setGeometry(QRect(150, 60, 81, 21))
        self.pixel_size_spinbox.setFont(font1)
        self.pixel_size_spinbox.setAlignment(Qt.AlignCenter)
        self.pixel_size_spinbox.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.pixel_size_spinbox.setDecimals(1)
        self.pixel_size_spinbox.setMinimum(1.000000000000000)
        self.pixel_size_spinbox.setMaximum(100.000000000000000)
        self.pixel_size_spinbox.setSingleStep(0.100000000000000)
        self.focal_length_label = QLabel(self.slm_parameters)
        self.focal_length_label.setObjectName(u"focal_length_label")
        self.focal_length_label.setGeometry(QRect(20, 90, 121, 21))
        self.focal_length_label.setFont(font1)
        self.focal_length_label.setLayoutDirection(Qt.LeftToRight)
        self.focal_length_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.focal_length_spinbox = QSpinBox(self.slm_parameters)
        self.focal_length_spinbox.setObjectName(u"focal_length_spinbox")
        self.focal_length_spinbox.setGeometry(QRect(150, 90, 81, 21))
        self.focal_length_spinbox.setFont(font1)
        self.focal_length_spinbox.setAlignment(Qt.AlignCenter)
        self.focal_length_spinbox.setMaximum(1000)
        self.focal_length_spinbox.setValue(500)
        self.screensize_combobox = QComboBox(self.slm_parameters)
        self.screensize_combobox.setObjectName(u"screensize_combobox")
        self.screensize_combobox.setGeometry(QRect(150, 30, 81, 22))
        self.objective_parameters = QGroupBox(Dialog)
        self.objective_parameters.setObjectName(u"objective_parameters")
        self.objective_parameters.setGeometry(QRect(20, 340, 251, 131))
        self.objective_parameters.setFont(font1)
        self.objective_magnification_label = QLabel(self.objective_parameters)
        self.objective_magnification_label.setObjectName(u"objective_magnification_label")
        self.objective_magnification_label.setGeometry(QRect(50, 30, 91, 21))
        self.objective_magnification_label.setFont(font1)
        self.objective_magnification_label.setLayoutDirection(Qt.LeftToRight)
        self.objective_magnification_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.objective_magnification_spinbox = QSpinBox(self.objective_parameters)
        self.objective_magnification_spinbox.setObjectName(u"objective_magnification_spinbox")
        self.objective_magnification_spinbox.setGeometry(QRect(150, 30, 81, 21))
        self.objective_magnification_spinbox.setFont(font1)
        self.objective_magnification_spinbox.setAlignment(Qt.AlignCenter)
        self.objective_magnification_spinbox.setMaximum(100)
        self.objective_magnification_spinbox.setValue(10)
        self.objective_na_label = QLabel(self.objective_parameters)
        self.objective_na_label.setObjectName(u"objective_na_label")
        self.objective_na_label.setGeometry(QRect(30, 60, 111, 21))
        self.objective_na_label.setFont(font1)
        self.objective_na_label.setLayoutDirection(Qt.LeftToRight)
        self.objective_na_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.objective_na_spinbox = QDoubleSpinBox(self.objective_parameters)
        self.objective_na_spinbox.setObjectName(u"objective_na_spinbox")
        self.objective_na_spinbox.setGeometry(QRect(150, 60, 81, 21))
        self.objective_na_spinbox.setFont(font1)
        self.objective_na_spinbox.setAlignment(Qt.AlignCenter)
        self.objective_na_spinbox.setMaximum(2.000000000000000)
        self.objective_na_spinbox.setSingleStep(0.010000000000000)
        self.objective_na_spinbox.setValue(0.250000000000000)
        self.tube_lens_spinbox = QSpinBox(self.objective_parameters)
        self.tube_lens_spinbox.setObjectName(u"tube_lens_spinbox")
        self.tube_lens_spinbox.setGeometry(QRect(150, 90, 81, 21))
        self.tube_lens_spinbox.setFont(font1)
        self.tube_lens_spinbox.setAlignment(Qt.AlignCenter)
        self.tube_lens_spinbox.setMaximum(1000)
        self.tube_lens_spinbox.setSingleStep(1)
        self.tube_lens_spinbox.setValue(200)
        self.tube_lens_label = QLabel(self.objective_parameters)
        self.tube_lens_label.setObjectName(u"tube_lens_label")
        self.tube_lens_label.setGeometry(QRect(30, 90, 111, 21))
        self.tube_lens_label.setFont(font1)
        self.tube_lens_label.setLayoutDirection(Qt.LeftToRight)
        self.tube_lens_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.mask_parameters = QGroupBox(Dialog)
        self.mask_parameters.setObjectName(u"mask_parameters")
        self.mask_parameters.setGeometry(QRect(20, 170, 251, 151))
        self.mask_parameters.setFont(font1)
        self.mask_od_label = QLabel(self.mask_parameters)
        self.mask_od_label.setObjectName(u"mask_od_label")
        self.mask_od_label.setGeometry(QRect(10, 30, 71, 21))
        self.mask_od_label.setFont(font1)
        self.mask_od_label.setLayoutDirection(Qt.LeftToRight)
        self.mask_od_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.mask_od_spinbox = QDoubleSpinBox(self.mask_parameters)
        self.mask_od_spinbox.setObjectName(u"mask_od_spinbox")
        self.mask_od_spinbox.setGeometry(QRect(90, 30, 81, 21))
        self.mask_od_spinbox.setFont(font1)
        self.mask_od_spinbox.setAlignment(Qt.AlignCenter)
        self.mask_od_spinbox.setDecimals(3)
        self.mask_od_spinbox.setMaximum(5.000000000000000)
        self.mask_od_spinbox.setSingleStep(0.001000000000000)
        self.mask_od_spinbox.setValue(3.824000000000000)
        self.mask_id_label = QLabel(self.mask_parameters)
        self.mask_id_label.setObjectName(u"mask_id_label")
        self.mask_id_label.setGeometry(QRect(10, 60, 71, 21))
        self.mask_id_label.setFont(font1)
        self.mask_id_label.setLayoutDirection(Qt.LeftToRight)
        self.mask_id_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.mask_id_spinbox = QDoubleSpinBox(self.mask_parameters)
        self.mask_id_spinbox.setObjectName(u"mask_id_spinbox")
        self.mask_id_spinbox.setGeometry(QRect(90, 60, 81, 21))
        self.mask_id_spinbox.setFont(font1)
        self.mask_id_spinbox.setAlignment(Qt.AlignCenter)
        self.mask_id_spinbox.setDecimals(3)
        self.mask_id_spinbox.setMaximum(5.000000000000000)
        self.mask_id_spinbox.setSingleStep(0.001000000000000)
        self.mask_id_spinbox.setValue(2.689000000000000)
        self.mask_od_na = QLabel(self.mask_parameters)
        self.mask_od_na.setObjectName(u"mask_od_na")
        self.mask_od_na.setGeometry(QRect(180, 30, 51, 21))
        self.mask_od_na.setFont(font1)
        self.mask_od_na.setLayoutDirection(Qt.LeftToRight)
        self.mask_od_na.setAlignment(Qt.AlignCenter)
        self.mask_id_na = QLabel(self.mask_parameters)
        self.mask_id_na.setObjectName(u"mask_id_na")
        self.mask_id_na.setGeometry(QRect(180, 60, 51, 21))
        self.mask_id_na.setFont(font1)
        self.mask_id_na.setLayoutDirection(Qt.LeftToRight)
        self.mask_id_na.setAlignment(Qt.AlignCenter)
        self.from_mask_file = QPushButton(self.mask_parameters)
        self.from_mask_file.setObjectName(u"from_mask_file")
        self.from_mask_file.setEnabled(False)
        self.from_mask_file.setGeometry(QRect(110, 100, 121, 31))
        self.from_mask_file.setFont(font1)
        self.system_parameters = QGroupBox(Dialog)
        self.system_parameters.setObjectName(u"system_parameters")
        self.system_parameters.setGeometry(QRect(20, 490, 251, 101))
        self.system_parameters.setFont(font1)
        self.wavelength_label = QLabel(self.system_parameters)
        self.wavelength_label.setObjectName(u"wavelength_label")
        self.wavelength_label.setGeometry(QRect(20, 30, 121, 21))
        self.wavelength_label.setFont(font1)
        self.wavelength_label.setLayoutDirection(Qt.LeftToRight)
        self.wavelength_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.wavelength_spinbox = QSpinBox(self.system_parameters)
        self.wavelength_spinbox.setObjectName(u"wavelength_spinbox")
        self.wavelength_spinbox.setGeometry(QRect(150, 30, 81, 21))
        self.wavelength_spinbox.setFont(font1)
        self.wavelength_spinbox.setAlignment(Qt.AlignCenter)
        self.wavelength_spinbox.setMinimum(350)
        self.wavelength_spinbox.setMaximum(1500)
        self.wavelength_spinbox.setValue(488)
        self.system_magnification_label = QLabel(self.system_parameters)
        self.system_magnification_label.setObjectName(u"system_magnification_label")
        self.system_magnification_label.setGeometry(QRect(10, 60, 131, 21))
        self.system_magnification_label.setFont(font1)
        self.system_magnification_label.setLayoutDirection(Qt.LeftToRight)
        self.system_magnification_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.system_magnification_spinbox = QDoubleSpinBox(self.system_parameters)
        self.system_magnification_spinbox.setObjectName(u"system_magnification_spinbox")
        self.system_magnification_spinbox.setGeometry(QRect(150, 60, 81, 21))
        self.system_magnification_spinbox.setFont(font1)
        self.system_magnification_spinbox.setAlignment(Qt.AlignCenter)
        self.system_magnification_spinbox.setDecimals(1)
        self.system_magnification_spinbox.setMaximum(500.000000000000000)
        self.system_magnification_spinbox.setSingleStep(0.100000000000000)
        self.system_magnification_spinbox.setValue(60.000000000000000)
        self.bessel_parameters = QGroupBox(Dialog)
        self.bessel_parameters.setObjectName(u"bessel_parameters")
        self.bessel_parameters.setGeometry(QRect(300, 20, 251, 141))
        self.bessel_parameters.setFont(font1)
        self.bessel_parameters.setFlat(False)
        self.bessel_parameters.setCheckable(True)
        self.bessel_parameters.setChecked(True)
        self.bessel_od_label = QLabel(self.bessel_parameters)
        self.bessel_od_label.setObjectName(u"bessel_od_label")
        self.bessel_od_label.setGeometry(QRect(10, 30, 71, 21))
        self.bessel_od_label.setFont(font1)
        self.bessel_od_label.setLayoutDirection(Qt.LeftToRight)
        self.bessel_od_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bessel_od_spinbox = QDoubleSpinBox(self.bessel_parameters)
        self.bessel_od_spinbox.setObjectName(u"bessel_od_spinbox")
        self.bessel_od_spinbox.setEnabled(False)
        self.bessel_od_spinbox.setGeometry(QRect(90, 30, 81, 21))
        self.bessel_od_spinbox.setFont(font1)
        self.bessel_od_spinbox.setAlignment(Qt.AlignCenter)
        self.bessel_od_spinbox.setDecimals(3)
        self.bessel_od_spinbox.setMaximum(10.000000000000000)
        self.bessel_od_spinbox.setSingleStep(0.001000000000000)
        self.bessel_od_spinbox.setValue(3.824000000000000)
        self.bessel_id_label = QLabel(self.bessel_parameters)
        self.bessel_id_label.setObjectName(u"bessel_id_label")
        self.bessel_id_label.setGeometry(QRect(10, 60, 71, 21))
        self.bessel_id_label.setFont(font1)
        self.bessel_id_label.setLayoutDirection(Qt.LeftToRight)
        self.bessel_id_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bessel_id_spinbox = QDoubleSpinBox(self.bessel_parameters)
        self.bessel_id_spinbox.setObjectName(u"bessel_id_spinbox")
        self.bessel_id_spinbox.setEnabled(False)
        self.bessel_id_spinbox.setGeometry(QRect(90, 60, 81, 21))
        self.bessel_id_spinbox.setFont(font1)
        self.bessel_id_spinbox.setAlignment(Qt.AlignCenter)
        self.bessel_id_spinbox.setDecimals(3)
        self.bessel_id_spinbox.setMaximum(10.000000000000000)
        self.bessel_id_spinbox.setSingleStep(0.001000000000000)
        self.bessel_id_spinbox.setValue(2.689000000000000)
        self.bessel_od_na = QLabel(self.bessel_parameters)
        self.bessel_od_na.setObjectName(u"bessel_od_na")
        self.bessel_od_na.setGeometry(QRect(180, 30, 51, 21))
        self.bessel_od_na.setFont(font1)
        self.bessel_od_na.setLayoutDirection(Qt.LeftToRight)
        self.bessel_od_na.setAlignment(Qt.AlignCenter)
        self.bessel_id_na = QLabel(self.bessel_parameters)
        self.bessel_id_na.setObjectName(u"bessel_id_na")
        self.bessel_id_na.setGeometry(QRect(180, 60, 51, 21))
        self.bessel_id_na.setFont(font1)
        self.bessel_id_na.setLayoutDirection(Qt.LeftToRight)
        self.bessel_id_na.setAlignment(Qt.AlignCenter)
        self.same_as_mask = QCheckBox(self.bessel_parameters)
        self.same_as_mask.setObjectName(u"same_as_mask")
        self.same_as_mask.setGeometry(QRect(20, 100, 121, 21))
        self.same_as_mask.setChecked(True)
        self.linear_bessel_array_parameters = QGroupBox(Dialog)
        self.linear_bessel_array_parameters.setObjectName(u"linear_bessel_array_parameters")
        self.linear_bessel_array_parameters.setGeometry(QRect(300, 180, 251, 211))
        self.linear_bessel_array_parameters.setFont(font1)
        self.linear_bessel_array_parameters.setFlat(False)
        self.linear_bessel_array_parameters.setCheckable(True)
        self.linear_bessel_array_parameters.setChecked(True)
        self.n_beams_label = QLabel(self.linear_bessel_array_parameters)
        self.n_beams_label.setObjectName(u"n_beams_label")
        self.n_beams_label.setGeometry(QRect(50, 30, 91, 21))
        self.n_beams_label.setFont(font1)
        self.n_beams_label.setLayoutDirection(Qt.LeftToRight)
        self.n_beams_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.n_beams_spinbox = QSpinBox(self.linear_bessel_array_parameters)
        self.n_beams_spinbox.setObjectName(u"n_beams_spinbox")
        self.n_beams_spinbox.setGeometry(QRect(150, 30, 81, 21))
        self.n_beams_spinbox.setFont(font1)
        self.n_beams_spinbox.setAlignment(Qt.AlignCenter)
        self.n_beams_spinbox.setMinimum(1)
        self.n_beams_spinbox.setMaximum(100)
        self.spacing_label = QLabel(self.linear_bessel_array_parameters)
        self.spacing_label.setObjectName(u"spacing_label")
        self.spacing_label.setGeometry(QRect(30, 130, 111, 21))
        self.spacing_label.setFont(font1)
        self.spacing_label.setLayoutDirection(Qt.LeftToRight)
        self.spacing_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.spacing_spinbox = QDoubleSpinBox(self.linear_bessel_array_parameters)
        self.spacing_spinbox.setObjectName(u"spacing_spinbox")
        self.spacing_spinbox.setGeometry(QRect(150, 130, 81, 21))
        self.spacing_spinbox.setFont(font1)
        self.spacing_spinbox.setAlignment(Qt.AlignCenter)
        self.spacing_spinbox.setDecimals(3)
        self.spacing_spinbox.setMaximum(100.000000000000000)
        self.spacing_spinbox.setSingleStep(0.001000000000000)
        self.spacing_spinbox.setValue(1.000000000000000)
        self.auto_spacing = QCheckBox(self.linear_bessel_array_parameters)
        self.auto_spacing.setObjectName(u"auto_spacing")
        self.auto_spacing.setGeometry(QRect(20, 170, 201, 21))
        self.fill_screen_checkbox = QCheckBox(self.linear_bessel_array_parameters)
        self.fill_screen_checkbox.setObjectName(u"fill_screen_checkbox")
        self.fill_screen_checkbox.setGeometry(QRect(20, 70, 111, 21))
        self.line = QFrame(self.linear_bessel_array_parameters)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 100, 211, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.fill_screen_spinbox = QSpinBox(self.linear_bessel_array_parameters)
        self.fill_screen_spinbox.setObjectName(u"fill_screen_spinbox")
        self.fill_screen_spinbox.setGeometry(QRect(150, 70, 81, 21))
        self.fill_screen_spinbox.setFont(font1)
        self.fill_screen_spinbox.setAlignment(Qt.AlignCenter)
        self.fill_screen_spinbox.setMaximum(100)
        self.fill_screen_spinbox.setValue(50)
        self.binarize_parameters = QGroupBox(Dialog)
        self.binarize_parameters.setObjectName(u"binarize_parameters")
        self.binarize_parameters.setGeometry(QRect(20, 610, 251, 101))
        self.binarize_parameters.setFont(font1)
        self.binarize_parameters.setCheckable(False)
        self.binarize_parameters.setChecked(False)
        self.cropping_factor_label = QLabel(self.binarize_parameters)
        self.cropping_factor_label.setObjectName(u"cropping_factor_label")
        self.cropping_factor_label.setGeometry(QRect(40, 60, 101, 21))
        self.cropping_factor_label.setFont(font1)
        self.cropping_factor_label.setLayoutDirection(Qt.LeftToRight)
        self.cropping_factor_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cropping_factor_spinbox = QDoubleSpinBox(self.binarize_parameters)
        self.cropping_factor_spinbox.setObjectName(u"cropping_factor_spinbox")
        self.cropping_factor_spinbox.setGeometry(QRect(150, 60, 81, 21))
        self.cropping_factor_spinbox.setFont(font1)
        self.cropping_factor_spinbox.setAlignment(Qt.AlignCenter)
        self.cropping_factor_spinbox.setMaximum(1.000000000000000)
        self.cropping_factor_spinbox.setSingleStep(0.010000000000000)
        self.cropping_factor_spinbox.setValue(0.050000000000000)
        self.simple_threshold = QCheckBox(self.binarize_parameters)
        self.simple_threshold.setObjectName(u"simple_threshold")
        self.simple_threshold.setGeometry(QRect(20, 30, 141, 21))
        self.simple_threshold.setChecked(True)
        self.simple_threshold.setTristate(False)
        self.regenerate = QPushButton(Dialog)
        self.regenerate.setObjectName(u"regenerate")
        self.regenerate.setGeometry(QRect(420, 500, 121, 31))
        self.regenerate.setFont(font)
        self.tiling_parameters = QGroupBox(Dialog)
        self.tiling_parameters.setObjectName(u"tiling_parameters")
        self.tiling_parameters.setGeometry(QRect(300, 410, 251, 71))
        self.tiling_parameters.setFont(font1)
        self.tiling_parameters.setFlat(False)
        self.tiling_parameters.setCheckable(True)
        self.tiling_parameters.setChecked(False)
        self.wavelength_spinbox_2 = QSpinBox(self.tiling_parameters)
        self.wavelength_spinbox_2.setObjectName(u"wavelength_spinbox_2")
        self.wavelength_spinbox_2.setGeometry(QRect(150, 30, 81, 21))
        self.wavelength_spinbox_2.setFont(font1)
        self.wavelength_spinbox_2.setAlignment(Qt.AlignCenter)
        self.wavelength_spinbox_2.setMinimum(350)
        self.wavelength_spinbox_2.setMaximum(1500)
        self.wavelength_spinbox_2.setValue(488)
        self.wavelength_label_2 = QLabel(self.tiling_parameters)
        self.wavelength_label_2.setObjectName(u"wavelength_label_2")
        self.wavelength_label_2.setGeometry(QRect(20, 30, 121, 21))
        self.wavelength_label_2.setFont(font1)
        self.wavelength_label_2.setLayoutDirection(Qt.LeftToRight)
        self.wavelength_label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.pre_mask_label.setText(QCoreApplication.translate("Dialog", u" Pre-Mask", None))
        self.post_mask_label.setText(QCoreApplication.translate("Dialog", u" Post-Mask", None))
        self.generated_label.setText(QCoreApplication.translate("Dialog", u" Generated", None))
        self.slm_parameters.setTitle(QCoreApplication.translate("Dialog", u" SLM ", None))
        self.screen_size_label.setText(QCoreApplication.translate("Dialog", u"Screen Size:", None))
        self.pixel_size_label.setText(QCoreApplication.translate("Dialog", u"Pixel Size (um):", None))
        self.focal_length_label.setText(QCoreApplication.translate("Dialog", u"Focal Length (mm):", None))
        self.objective_parameters.setTitle(QCoreApplication.translate("Dialog", u" Objective ", None))
        self.objective_magnification_label.setText(QCoreApplication.translate("Dialog", u"Magnification:", None))
        self.objective_na_label.setText(QCoreApplication.translate("Dialog", u"NA:", None))
        self.tube_lens_label.setText(QCoreApplication.translate("Dialog", u"Tube Lens (mm):", None))
        self.mask_parameters.setTitle(QCoreApplication.translate("Dialog", u" Mask ", None))
        self.mask_od_label.setText(QCoreApplication.translate("Dialog", u"OD (mm):", None))
        self.mask_id_label.setText(QCoreApplication.translate("Dialog", u"ID (mm):", None))
        self.mask_od_na.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.mask_id_na.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.from_mask_file.setText(QCoreApplication.translate("Dialog", u"From Mask File", None))
        self.system_parameters.setTitle(QCoreApplication.translate("Dialog", u" System ", None))
        self.wavelength_label.setText(QCoreApplication.translate("Dialog", u"Wavelength (nm):", None))
        self.system_magnification_label.setText(QCoreApplication.translate("Dialog", u"Overall Magnification:", None))
        self.bessel_parameters.setTitle(QCoreApplication.translate("Dialog", u" Bessel ", None))
        self.bessel_od_label.setText(QCoreApplication.translate("Dialog", u"OD (mm):", None))
        self.bessel_id_label.setText(QCoreApplication.translate("Dialog", u"ID (mm):", None))
        self.bessel_od_na.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.bessel_id_na.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.same_as_mask.setText(QCoreApplication.translate("Dialog", u"Same as mask", None))
        self.linear_bessel_array_parameters.setTitle(QCoreApplication.translate("Dialog", u" Linear Bessel Array ", None))
        self.n_beams_label.setText(QCoreApplication.translate("Dialog", u"# Beams:", None))
        self.spacing_label.setText(QCoreApplication.translate("Dialog", u"Spacing (um):", None))
        self.auto_spacing.setText(QCoreApplication.translate("Dialog", u"Determine spacing from NA", None))
        self.fill_screen_checkbox.setText(QCoreApplication.translate("Dialog", u"Fill screen (%):", None))
        self.binarize_parameters.setTitle(QCoreApplication.translate("Dialog", u" Binarize ", None))
        self.cropping_factor_label.setText(QCoreApplication.translate("Dialog", u"Cropping Factor:", None))
        self.simple_threshold.setText(QCoreApplication.translate("Dialog", u"Simple Threshold", None))
        self.regenerate.setText(QCoreApplication.translate("Dialog", u"Regenerate", None))
        self.tiling_parameters.setTitle(QCoreApplication.translate("Dialog", u" Tiling ", None))
        self.wavelength_label_2.setText(QCoreApplication.translate("Dialog", u"Focus (um):", None))
    # retranslateUi

